(function(g){var window=this;var mCa=function(a,b){return g.Ub(a,b)},s6=function(a){g.Im(a,"zx",g.vb());
return a},t6=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Lm(a.g,b,c)},nCa=function(a,b){var c=[];
g.xk(b,function(a){try{var b=g.jD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.iD(b)&&c.push(a):c.push(a)},a);
return c},oCa=function(a,b){var c=nCa(a,b);
(0,g.B)(c,function(a){g.jD.prototype.remove.call(this,a)},a)},pCa=function(a){if(a.Ad){if(a.Ad.locationOverrideToken)return{locationOverrideToken:a.Ad.locationOverrideToken};
if(null!=a.Ad.latitudeE7&&null!=a.Ad.longitudeE7)return{latitudeE7:a.Ad.latitudeE7,longitudeE7:a.Ad.longitudeE7}}return null},qCa=function(a,b,c,d){var e=new g.zm(null,void 0);
a&&g.Am(e,a);b&&g.Bm(e,b);c&&g.Cm(e,c);d&&g.Dm(e,d);return e},rCa=function(a){g.fG[a]&&(a=g.fG[a],(0,g.B)(a,function(a){g.dG[a]&&delete g.dG[a]}),a.length=0)},sCa=function(a){var b=g.cG();
if(b)if(b.clear(a),a)rCa(a);else for(var c in g.fG)rCa(c)},u6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.tm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",tCa(this,a.capabilities||""),uCa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},tCa=function(a,b){a.capabilities.clear();
(0,g.Ld)(b.split(","),g.Ea(mCa,vCa)).forEach(function(b){a.capabilities.add(b)})},uCa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},v6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},w6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},wCa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},xCa=function(a){return new v6(a)},yCa=function(a){return g.ya(a)?(0,g.G)(a,xCa):[]},x6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},y6=function(a){return g.ya(a)?"["+(0,g.G)(a,x6).join(",")+"]":"null"},z6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},zCa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},A6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},B6=function(a,b){return g.Ja(a,function(a){return w6(a,b)})},ACa=function(){var a=(0,g.ZG)();
a&&oCa(a,a.g.Pd(!0))},C6=function(){var a=g.bH("yt-remote-connected-devices")||[];
g.fb(a);return a},BCa=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},CCa=function(a){g.aH("yt-remote-connected-devices",a,86400)},E6=function(){if(D6)return D6;
var a=g.bH("yt-remote-device-id");a||(a=z6(),g.aH("yt-remote-device-id",a,31536E3));for(var b=C6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return D6=d},F6=function(){var a=C6(),b=E6();
g.Na(a,b);g.dH()&&g.ib(a,b);a=BCa(a);if(g.Oa(a))try{g.MG("remote_sid")}catch(c){}else try{g.LG("remote_sid",a.join(","),-1)}catch(c){}},DCa=function(){return g.bH("yt-remote-session-browser-channel")},ECa=function(){return g.bH("yt-remote-local-screens")||[]},FCa=function(){g.aH("yt-remote-lounge-token-expiration",!0,86400)},GCa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(ECa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.fm)(c,function(a){return!g.Na(b,a)})&&FCa();
g.aH("yt-remote-local-screens",a,31536E3)},HCa=function(a,b){g.aH("yt-remote-session-browser-channel",a);
g.aH("yt-remote-session-screen-id",b);var c=C6(),d=E6();g.Na(c,d)||c.push(d);CCa(c);F6()},G6=function(a){a||(g.cH("yt-remote-session-screen-id"),g.cH("yt-remote-session-video-id"));
F6();a=C6();g.Sa(a,E6());CCa(a)},ICa=function(){if(!H6){var a=g.uD();
a&&(H6=new g.dD(a))}return H6?!!H6.get("yt-remote-use-staging-server"):!1},JCa=function(){var a=window.document.createElement("a");
g.Yc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.zb(a)},KCa=function(a,b){var c=g.Ed("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.$c(c,g.de("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},LCa=function(){var a=JCa(),b=window.document.getElementById(a),c=b&&g.oF(b,"loaded");
c||b&&!c||(b=KCa(a,function(){g.oF(b,"loaded")||(g.nF(b,"loaded","true"),g.jG(a),g.cE(g.Ea(sCa,a),0))}))},I6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},MCa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},J6=function(a){a.length?NCa(a.shift(),function(){J6(a)}):K6()},OCa=function(a){return"chrome-extension://"+a+L6},NCa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},M6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},K6=function(){var a=MCa();
a&&a(!1,"No cast extension found")},N6=function(){if(PCa){var a=2,b=MCa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;NCa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",K6,c)}},QCa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(N6(),a({command:"cast.sender.init"}))},RCa=function(){N6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);J6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+L6,"//www.gstatic.com/eureka/clank"+L6])},O6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.fd=b;this.B=(0,g.z)(this.JI,this);this.g=!1;this.l=0;this.o=this.ya=null;this.A=[]},P6=function(){},Q6=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Pm(this);this.l=new g.ug;this.l.setInterval(250)},TCa=function(a,b,c){a.zj=1;
a.eh=s6(b.clone());a.Ei=c;a.B=!0;SCa(a,null)},R6=function(a,b,c,d,e){a.zj=1;
a.eh=s6(b.clone());a.Ei=null;a.B=c;e&&(a.hD=!1);SCa(a,d)},SCa=function(a,b){a.gk=(0,g.F)();
S6(a);a.Bh=a.eh.clone();t6(a.Bh,"t",a.C);a.lm=0;a.Rc=a.g.fr(a.g.fm()?b:null);0<a.Kr&&(a.bp=new g.Xk((0,g.z)(a.vE,a,a.Rc),a.Kr));a.W.U(a.Rc,"readystatechange",a.fU);var c=a.fi?g.bc(a.fi):{};a.Ei?(a.Pp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.Bh,a.Pp,a.Ei,c)):(a.Pp="GET",a.hD&&!g.Ad&&(c.Connection="close"),a.Rc.send(a.Bh,a.Pp,null,c));a.g.sf(1)},WCa=function(a,b,c){for(var d=!0;!a.Ph&&a.lm<c.length;){var e=UCa(a,c);
if(e==T6){4==b&&(a.fh=4,U6(15),d=!1);break}else if(e==VCa){a.fh=4;U6(16);d=!1;break}else V6(a,e)}4==b&&0==c.length&&(a.fh=1,U6(17),d=!1);a.yf=a.yf&&d;d||(W6(a),X6(a))},UCa=function(a,b){var c=a.lm,d=b.indexOf("\n",c);
if(-1==d)return T6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return VCa;d+=1;if(d+c>b.length)return T6;var e=b.substr(d,c);a.lm=d+c;return e},YCa=function(a,b){a.gk=(0,g.F)();
S6(a);var c=b?window.location.hostname:"";a.Bh=a.eh.clone();g.Im(a.Bh,"DOMAIN",c);g.Im(a.Bh,"t",a.C);try{a.zf=new window.ActiveXObject("htmlfile")}catch(n){W6(a);a.fh=7;U6(22);X6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in Y6)k=Y6[l];else if(l in XCa)k=Y6[l]=XCa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=Y6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.ad(g.vc("b/12014412"),d);a.zf.open();a.zf.write(g.Sc(c));a.zf.close();a.zf.parentWindow.m=(0,g.z)(a.lT,a);a.zf.parentWindow.d=(0,g.z)(a.uC,a,!0);a.zf.parentWindow.rpcClose=(0,g.z)(a.uC,a,!1);c=a.zf.createElement("DIV");a.zf.parentWindow.document.body.appendChild(c);d=g.Jc(a.Bh.toString());d=g.pb(g.Gc(d));d=g.ad(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Sc(d);
a.g.sf(1)},S6=function(a){a.rv=(0,g.F)()+a.A;
ZCa(a,a.A)},ZCa=function(a,b){if(null!=a.Ak)throw Error("WatchDog timer not null");
a.Ak=Z6((0,g.z)(a.BT,a),b)},$6=function(a){a.Ak&&(g.w.clearTimeout(a.Ak),a.Ak=null)},X6=function(a){a.g.Ey()||a.Ph||a.g.Lo(a)},W6=function(a){$6(a);
g.bf(a.bp);a.bp=null;a.l.stop();g.Vm(a.W);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.zf&&(a.zf=null)},V6=function(a,b){try{a.g.nC(a,b),a.g.sf(4)}catch(c){}},aDa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;$Ca(a,b,function(e){e?c(!0):g.w.setTimeout(function(){aDa(a,b,c,d,f)},f)})}},$Ca=function(a,b,c){var d=new window.Image;
d.onload=function(){try{a7(d),c(!0)}catch(e){}};
d.onerror=function(){try{a7(d),c(!1)}catch(e){}};
d.onabort=function(){try{a7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{a7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},a7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},bDa=function(a){this.g=a;
this.l=new P6},cDa=function(a){var b=b7(a.g,a.Gk,"/mail/images/cleardot.gif");
s6(b);aDa(b.toString(),5E3,(0,g.z)(a.UH,a),3,2E3);a.sf(1)},d7=function(a){var b=a.g.H;
if(null!=b)U6(5),b?(U6(11),c7(a.g,a,!1)):(U6(12),c7(a.g,a,!0));else if(a.qe=new Q6(a,void 0,void 0,void 0),a.qe.fi=a.Ir,b=a.g,b=b7(b,b.fm()?a.il:null,a.Jr),U6(5),!g.yd||g.rc(10))t6(b,"TYPE","xmlhttp"),R6(a.qe,b,!1,a.il,!1);else{t6(b,"TYPE","html");var c=a.qe;a=!!a.il;c.zj=3;c.eh=s6(b.clone());YCa(c,a)}},e7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new P6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},dDa=function(a,b){this.g=a;
this.map=b;this.context=null},eDa=function(a){g.df.call(this,"statevent",a)},fDa=function(a,b){g.df.call(this,"timingevent",a);
this.size=b},gDa=function(a){g.df.call(this,"serverreachability",a)},jDa=function(a){hDa(a);
if(3==a.g){var b=a.Nl++,c=a.Hn.clone();g.Im(c,"SID",a.o);g.Im(c,"RID",b);g.Im(c,"TYPE","terminate");f7(a,c);b=new Q6(a,a.o,b,void 0);b.zj=2;b.eh=s6(c.clone());(new window.Image).src=b.eh;b.gk=(0,g.F)();S6(b)}iDa(a)},kDa=function(a){a.qI(1,0);
a.Hn=b7(a,null,a.Hr);g7(a)},hDa=function(a){a.Tg&&(a.Tg.abort(),a.Tg=null);
a.xc&&(a.xc.cancel(),a.xc=null);a.rg&&(g.w.clearTimeout(a.rg),a.rg=null);h7(a);a.Vd&&(a.Vd.cancel(),a.Vd=null);a.Vg&&(g.w.clearTimeout(a.Vg),a.Vg=null)},lDa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new dDa(a.aP++,b));2!=a.g&&3!=a.g||g7(a)},g7=function(a){a.Vd||a.Vg||(a.Vg=Z6((0,g.z)(a.sC,a),0),a.mj=0)},nDa=function(a,b){if(1==a.g){if(!b){a.Nl=Math.floor(1E5*Math.random());
var c=a.Nl++,d=new Q6(a,"",c,void 0);d.fi=null;var e=i7(a),f=a.Hn.clone();g.Im(f,"RID",c);g.Im(f,"CVER","1");f7(a,f);TCa(d,f,e);a.Vd=d;a.g=2}}else 3==a.g&&(b?mDa(a,b):0==a.l.length||a.Vd||mDa(a))},mDa=function(a,b){if(b)if(6<a.Rh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Nl-1;var d=i7(a)}else c=b.D,d=b.Ei;else c=a.Nl++,d=i7(a);var e=a.Hn.clone();g.Im(e,"SID",a.o);g.Im(e,"RID",c);g.Im(e,"AID",a.Mj);f7(a,e);c=new Q6(a,a.o,c,a.mj+1);c.fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Vd=c;TCa(c,e,d)},f7=function(a,b){if(a.rd){var c=a.rd.iy();
c&&g.Ib(c,function(a,c){g.Im(b,c,a)})}},i7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Rh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Rh?e:f-d;try{g.Ib(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},oDa=function(a){a.xc||a.rg||(a.D=1,a.rg=Z6((0,g.z)(a.rC,a),0),a.Yi=0)},j7=function(a){if(a.xc||a.rg||3<=a.Yi)return!1;
a.D++;a.rg=Z6((0,g.z)(a.rC,a),pDa(a,a.Yi));a.Yi++;return!0},c7=function(a,b,c){a.Op=c;
a.Nf=b.yg;a.C||kDa(a)},h7=function(a){null!=a.Th&&(g.w.clearTimeout(a.Th),a.Th=null)},pDa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},k7=function(a,b){if(2==b||9==b){var c=null;
a.rd&&(c=null);var d=(0,g.z)(a.ZU,a);c||(c=new g.zm("//www.google.com/images/cleardot.gif"),s6(c));$Ca(c.toString(),1E4,d)}else U6(2);qDa(a,b)},qDa=function(a,b){a.g=0;
a.rd&&a.rd.ax(b);iDa(a);hDa(a)},iDa=function(a){a.g=0;
a.Nf=-1;if(a.rd)if(0==a.A.length&&0==a.l.length)a.rd.Qq();else{g.Wa(a.A);var b=g.Wa(a.l);a.A.length=0;a.l.length=0;a.rd.Qq(b)}},b7=function(a,b,c){var d=g.Jm(c);
if(""!=d.l)b&&g.Bm(d,b+"."+d.l),g.Cm(d,d.B);else{var e=window.location;d=qCa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Rk&&g.Ib(a.Rk,function(a,b){g.Im(d,b,a)});
g.Im(d,"VER",a.Rh);f7(a,d);return d},Z6=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},U6=function(a){l7.dispatchEvent(new eDa(l7,a))},rDa=function(){},sDa=function(a,b){this.action=a;
this.params=b||{}},m7=function(a,b){g.K.call(this);
this.g=new g.cu(this.cT,0,this);g.M(this,this.g);this.fd=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},n7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.cD;this.l=new m7(this.GV,this);this.g=this.Wa=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.L=c||!1},tDa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Op,sessionId:a.g.o,arrayId:a.g.Mj}},uDa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&nDa(a.g),jDa(a.g));a.F=0},o7=function(a){return!!a.g&&3==a.g.g},vDa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},p7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Kg(a)||"";b&&(this.port=":"+b);this.domain=g.Jg(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.l=!1))},q7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Ug(c+b,{})},r7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),xd:g.Ea(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.sE(b,a)},zDa=function(){var a=wDa;
xDa();s7.push(a);yDa(s7)},t7=function(a,b){xDa();
var c=s7,d=ADa(a,String(b));g.Oa(c)?BDa(d):(yDa(c),(0,g.B)(c,function(a){a(d)}))},xDa=function(){s7||(s7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",s7,void 0))},BDa=function(a){var b=(u7+1)%50;
u7=b;v7[b]=a;w7||(w7=49==b)},yDa=function(a){var b=v7;
if(b[0]){var c=u7,d=w7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
v7=Array(50);u7=-1;w7=!1}},ADa=function(a,b){var c=((0,g.F)()-CDa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},x7=function(a){g.VF.call(this);
this.D=a;this.g=[]},DDa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},EDa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Ld)(a.g,function(a){return!!A6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=DDa(a,b[d])||c;return c},FDa=function(a,b){var c=a.g.length;
a.g=(0,g.Ld)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},y7=function(a,b,c,d){g.VF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.ya=window.NaN},A7=function(a){x7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;z7(this);this.info("Initializing with "+y6(this.g))},GDa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=q7(a.o,"/pairing/get_lounge_token_batch");
r7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.YI,a),(0,g.z)(a.XI,a))}},z7=function(a){var b=yCa(ECa());
b=(0,g.Ld)(b,function(a){return!a.uuid});
return EDa(a,b)},B7=function(a,b){GCa((0,g.G)(a.g,wCa));
b&&FCa()},D7=function(a,b){g.VF.call(this);
this.C=b;var c=g.bH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;C7("Initialized with "+g.Bg(this.g))},HDa=function(a,b,c){var d=q7(a.B,"/pairing/get_screen_availability");
r7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},E7=function(a,b){a:if(g.Mb(b)!=g.Mb(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(C7("Updated online screens: "+g.Bg(a.g)),a.g=b,a.R("screenChange"));IDa(a)},F7=function(a){(0,window.isNaN)(a.o)||g.eE(a.o);
a.o=g.cE((0,g.z)(a.Eu,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},C7=function(a){t7("OnlineScreenService",a)},JDa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},IDa=function(a){a=g.Qb(g.Jb(a.g,function(a){return a}));
g.fb(a);a.length?g.aH("yt-remote-online-screen-ids",a.join(","),60):g.cH("yt-remote-online-screen-ids")},G7=function(a){x7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};KDa(this)},MDa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.je();if(k=(c?B6(k,c):null)||B6(k,b)){k.uuid=b;var l=H7(a,k);HDa(a.l,l,function(a){e(a?l:null)})}else c?LDa(a,c,(0,g.z)(function(a){var f=H7(this,new v6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));HDa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},NDa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},LDa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.sE(q7(a.C,"/pairing/get_lounge_token_batch"),e)},ODa=function(a){a.g=a.o.je();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+y6(a.g))},KDa=function(a){I7(a);
a.o=new A7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.nJ,a));ODa(a);a.A=yCa(g.bH("yt-remote-automatic-screen-cache")||[]);I7(a);a.info("Initializing automatic screens: "+y6(a.A));a.l=new D7(a.C,(0,g.z)(a.je,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},H7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=B6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.aH("yt-remote-automatic-screen-cache",(0,g.G)(a.A,wCa)));I7(a);a.B[b.uuid]=b.id;g.aH("yt-remote-device-id-map",a.B,31536E3);return b},I7=function(a){a.B=g.bH("yt-remote-device-id-map")||{}},J7=function(a,b,c){g.VF.call(this);
this.L=c;this.H=a;this.l=b;this.o=null},K7=function(a,b){t7(a.L,b)},L7=function(a,b){J7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.MV,this);this.B=(0,g.z)(this.OT,this);this.A=g.cE((0,g.z)(function(){PDa(this,null)},this),12E4)},QDa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Bg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){K7(this,"Failed to send message: getMdxSessionStatus.")},a)):K7(a,"Sending yt message without session: "+g.Bg(b))},PDa=function(a,b){g.eE(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Mo,a),d=(0,g.z)(a.pe,a);a.wy(b,c,d,5)}}else a.pe(Error("Waiting for session status timed out."))},M7=function(a,b,c){J7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.PV,this);this.g=g.y},RDa=function(a){a.g=a.H.CE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Mo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.pe(a)},a))},SDa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}ICa()&&(b.env_useStageMdx=1);return g.Sg(b)},N7=function(a,b){J7.call(this,a,b,"ManualSession");
this.g=g.cE((0,g.z)(this.Oj,this,null),150)},O7=function(a,b,c,d){g.VF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.oS,this)},TDa=function(a,b){return b?g.Ja(a.o,function(a){return w6(b,a.label)},a):null},P7=function(a){t7("Controller",a)},wDa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},Q7=function(a){return a.B||!!a.o.length||!!a.g},R7=function(a,b,c){b!=a.g&&(g.bf(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.pC,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.Oj(null)):a.R("yt-remote-cast2-session-change",null))},UDa=function(a){var b=a.l.BE(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&w6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=TDa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},$Da=function(a,b,c,d,e,f,k){VDa()?WDa(b,e,f,k)&&(T7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?XDa(a,c):(window.__onGCastApiAvailable=function(b,d){b?XDa(a,c):(U7("Failed to load cast API: "+d),V7(!1),T7(!1),g.cH("yt-remote-cast-available"),g.cH("yt-remote-cast-receiver"),YDa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):LCa():M6("CriOS")?QCa():M6("Android")&&M6("Chrome/")&&window.navigator.presentation?RCa():window.chrome&&window.navigator.presentation&&!M6("Edge")?(N6(),J6(ZDa.map(OCa))):K6())):S7("Cannot initialize because not running Chrome")},YDa=function(){S7("dispose");
var a=W7();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);aEa(!1);g.hG(X7);X7.length=0},Y7=function(){return!!g.bH("yt-remote-cast-installed")},bEa=function(){var a=g.bH("yt-remote-cast-receiver");
return a?a.friendlyName:null},cEa=function(){S7("clearCurrentReceiver");
g.cH("yt-remote-cast-receiver")},dEa=function(){return Y7()?W7()?W7().getCastSession():(U7("getCastSelector: Cast is not initialized."),null):(U7("getCastSelector: Cast API is not installed!"),null)},$7=function(){Y7()?W7()?Z7()?(S7("Requesting cast selector."),W7().requestSession()):(S7("Wait for cast API to be ready to request the session."),X7.push(g.gG("yt-remote-cast2-api-ready",$7))):U7("requestCastSelector: Cast is not initialized."):U7("requestCastSelector: Cast API is not installed!")},a8=
function(a,b){Z7()?W7().setConnectedScreenStatus(a,b):U7("setConnectedScreenStatus called before ready.")},VDa=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.KI||a},eEa=function(a,b){W7().init(a,b)},WDa=function(a,b,c,d){var e=!1;
W7()||(a=new O7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.aH("yt-remote-cast-available",a);g.kG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){S7("onReceiverSelected: "+a.friendlyName);
g.aH("yt-remote-cast-receiver",a);g.kG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){S7("onReceiverResumed: "+a.friendlyName);
g.aH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){S7("onSessionChange: "+x6(a));
a||g.cH("yt-remote-cast-receiver");g.kG("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
S7("cloudview.createSingleton_: "+e);return e},W7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},XDa=function(a,b){V7(!0);
T7(!1);eEa(a,function(a){a?(aEa(!0),g.jG("yt-remote-cast2-api-ready")):(U7("Failed to initialize cast API."),V7(!1),g.cH("yt-remote-cast-available"),g.cH("yt-remote-cast-receiver"),YDa());b(a)})},S7=function(a){t7("cloudview",a)},U7=function(a){t7("cloudview",a)},V7=function(a){S7("setCastInstalled_ "+a);
g.aH("yt-remote-cast-installed",a)},Z7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},aEa=function(a){S7("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},T7=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},b8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Qf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},c8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Qf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},d8=function(a){return a.kb()?((0,g.F)()-a.D)/1E3:0},e8=function(a,b){a.F=b;
a.D=(0,g.F)()},f8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},g8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&c8(a)},h8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.Qf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},j8=function(a,b){g.VF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.tC;this.o=this.l=null;this.H=(0,g.z)(this.KP,this);this.D=(0,g.z)(this.Ql,this);this.F=(0,g.z)(this.JP,this);this.I=(0,g.z)(this.WP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Av,this),fEa(this))):c=3;0!=c&&(b?this.Av(c):g.cE((0,g.z)(function(){this.Av(c)},this),0));
var d=dEa();d&&i8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},k8=function(a){return new b8(a.A.getPlayerContextData())},fEa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.jS,a),this))},a)},gEa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},l8=function(a,b){50>a.B.Dc()&&g.vC(a.B,b)},n8=function(a,b,c){var d=k8(a);
e8(d,c);-1E3!=d.g&&(d.g=b);m8(a,d)},o8=function(a,b,c){a.A.sendMessage(b,c)},m8=function(a,b){gEa(a);
a.A.setPlayerContextData(h8(b));fEa(a)},i8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Ql(null));
a.o=b;a.o&&(t7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Ql(a.o.media[0]))},hEa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=k8(a);b.contentId!=d.videoId&&t7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;e8(d,a.l.getEstimatedTime());m8(a,d)}else t7("CP","No cast media video. Ignoring state update.")},p8=function(a,b,c){return(0,g.z)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),o8(this,b,c))},a)},q8=function(a,b,c){g.VF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.L=window.NaN;this.T=[];this.A=this.D=this.o=this.Xa=this.g=null;this.pa=a;this.T.push(g.EF(window,"beforeunload",(0,g.z)(this.NI,this)));this.l=[];this.Xa=new b8;this.Z=b.id;this.g=iEa(this,c);this.g.subscribe("handlerOpened",this.OP,this);this.g.subscribe("handlerClosed",this.LP,this);this.g.subscribe("handlerError",this.MP,this);this.g.subscribe("handlerMessage",this.NP,this);vDa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Xa.videoId;g.dH()&&g.aH("yt-remote-session-video-id",a)},this)},r8=function(a){t7("conn",a)},iEa=function(a,b){return new n7(q7(a.pa,"/bc"),b)},s8=function(a,b){a.R("proxyStateChange",b)},jEa=function(a){a.B=g.cE((0,g.z)(function(){r8("Connecting timeout");
this.C(1)},a),2E4)},t8=function(a){g.eE(a.B);
a.B=window.NaN},u8=function(a){g.eE(a.L);
a.L=window.NaN},kEa=function(a){v8(a);
a.K=g.cE((0,g.z)(function(){w8(this,"getNowPlaying")},a),2E4)},v8=function(a){g.eE(a.K);
a.K=window.NaN},mEa=function(a,b){b&&(t8(a),u8(a));
b==(o7(a.g)&&(0,window.isNaN)(a.B))?b&&(s8(a,1),w8(a,"getSubtitlesTrack")):b?(a.X()&&a.Xa.reset(),s8(a,1),w8(a,"getNowPlaying"),lEa(a)):a.C(1)},nEa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Xa.videoId&&(g.Xb(b.params)?a.Xa.l=null:a.Xa.l=b.params,a.R("remotePlayerChange"))},oEa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Xa.listId=b.params.listId||a.Xa.listId;g8(a.Xa,c,d);a.R("remoteQueueChange")},qEa=function(a,b){b.params=b.params||{};
oEa(a,b);pEa(a,b);a.R("autoplayDismissed")},pEa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
e8(a.Xa,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Xa.g&&(c=-1E3);a.Xa.g=c;c=Number(b.params.loadedTime);a.Xa.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Xa.H=(0,window.isNaN)(c)?0:c;c=a.Xa;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Xa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Xa.g?kEa(a):v8(a);
a.R("remotePlayerChange")},rEa=function(a,b){if(-1E3!=a.Xa.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Xa.g=c;c=(0,window.parseInt)(b.params.currentTime,10);e8(a.Xa,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},sEa=function(a,b){var c="true"==b.params.muted;
a.Xa.volume=(0,window.parseInt)(b.params.volume,10);a.Xa.muted=c;a.R("remotePlayerChange")},tEa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},uEa=function(a,b){var c="true"==b.params.hasNext;
a.Xa.Qf="true"==b.params.hasPrevious;a.Xa.hasNext=c;a.R("previousNextChange")},lEa=function(a){g.eE(a.I);
a.I=g.cE((0,g.z)(a.C,a,1),864E5)},w8=function(a,b,c){c?r8("Sending: action="+b+", params="+g.Bg(c)):r8("Sending: action="+b);
a.g.sendMessage(b,c)},x8=function(a){x7.call(this,"ScreenServiceProxy");
this.ed=a;this.l=[];this.l.push(this.ed.$_s("screenChange",(0,g.z)(this.KV,this)));this.l.push(this.ed.$_s("onlineScreenChange",(0,g.z)(this.KR,this)))},zEa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.XD("MDX_CONFIG")||b;ACa();F6();y8||(y8=new p7(b?b.loungeApiHost:void 0),ICa()&&(y8.g="/api/loungedev"));z8||(z8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",z8,void 0));vEa();var c=A8();if(!c){var d=new G7(y8);g.va("yt.mdx.remote.screenService_",d,void 0);c=A8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);$Da(a,d,function(a){a?B8()&&a8(B8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.kG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),C8("Initializing: "+g.Bg(b)),D8.push(g.gG("yt-remote-cast2-availability-change",function(){g.kG("yt-remote-receiver-availability-change")})),D8.push(g.gG("yt-remote-cast2-receiver-selected",function(){E8(null);
g.kG("yt-remote-auto-connect","cast-selector-receiver")})),D8.push(g.gG("yt-remote-cast2-receiver-resumed",function(){g.kG("yt-remote-receiver-resumed","cast-selector-receiver")})),D8.push(g.gG("yt-remote-cast2-session-change",wEa)),D8.push(g.gG("yt-remote-connection-change",function(a){a?a8(B8(),"YouTube TV"):F8()||(a8(null,null),cEa())})),a=G8(),b.isAuto&&(a.id+="#dial"),g.aG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),C8(" -- with channel params: "+
g.Bg(a)),xEa(a),c.start(),B8()||yEa())},BEa=function(){var a=AEa();
Y7()&&g.bH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},AEa=function(){var a=A8().ed.$_gos();
var b=H8();b&&I8()&&(A6(a,b)||a.push(b));return zCa(a)},J8=function(){var a=CEa();
!a&&Y7()&&bEa()&&(a={key:"cast-selector-receiver",name:bEa()});return a},CEa=function(){var a=AEa(),b=H8();
b||(b=F8());return g.Ja(a,function(a){return b&&w6(b,a.key)?!0:!1})},H8=function(){var a=B8();
if(!a)return null;var b=A8().je();return B6(b,a)},wEa=function(a){C8("remote.onCastSessionChange_: "+x6(a));
if(a){var b=H8();b&&b.id==a.id?a8(b.id,"YouTube TV"):(b&&K8(),L8(a,1))}else I8()&&K8()},K8=function(){Z7()?W7().stopSession():U7("stopSession called before API ready.");
var a=I8();a&&(a.disconnect(1),M8(null))},N8=function(){var a=I8();
return!!a&&3!=a.getProxyState()},C8=function(a){t7("remote",a)},A8=function(){if(!O8){var a=g.x("yt.mdx.remote.screenService_");
O8=a?new x8(a):null}return O8},B8=function(){return g.x("yt.mdx.remote.currentScreenId_")},DEa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},EEa=function(){return g.x("yt.mdx.remote.connectData_")},E8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},I8=function(){return g.x("yt.mdx.remote.connection_")},M8=function(a){var b=I8();
E8(null);a||DEa("");g.va("yt.mdx.remote.connection_",a,void 0);z8&&((0,g.B)(z8,function(b){b(a)}),z8.length=0);
b&&!a?g.kG("yt-remote-connection-change",!1):!b&&a&&g.kG("yt-remote-connection-change",!0)},F8=function(){var a=g.dH();
if(!a)return null;var b=A8().je();return B6(b,a)},L8=function(a,b){H8()&&H8();
DEa(a.id);var c=new q8(y8,a,G8());c.connect(b,EEa());c.subscribe("beforeDisconnect",function(a){g.kG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){I8()&&M8(null)});
M8(c)},yEa=function(){var a=F8();
a?(C8("Resume connection to: "+x6(a)),L8(a,0)):(G6(),cEa(),C8("Skipping connecting because no session screen found."))},vEa=function(){var a=G8();
if(g.Xb(a)){a=E6();var b=g.bH("yt-remote-session-name")||"",c=g.bH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},G8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},xEa=function(a){a?(g.aH("yt-remote-session-app",a.app),g.aH("yt-remote-session-name",a.name)):(g.cH("yt-remote-session-app"),g.cH("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},P8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.SF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.dR);this.o.O(b,"captionschanged",this.IP);this.o.O(b,"captionssettingschanged",this.PD);this.o.O(b,"videoplayerreset",this.No);this.o.O(b,"mdxautoplaycancel",this.TH);this.T=this.o.O(b,"onVolumeChange",this.ZB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.mC,this);c.subscribe("remotePlayerChange",this.Tl,this);c.subscribe("remoteQueueChange",this.No,this);c.subscribe("autoplayUpNext",this.JB,
this);c.subscribe("previousNextChange",this.jC,this);c.subscribe("nowAutoplaying",this.bC,this);c.subscribe("autoplayDismissed",this.IB,this);this.suggestion=null;this.H=new g.HP(64);this.A=new g.cu(this.LD,500,this);g.M(this,this.A);this.B=new g.cu(this.MD,1E3,this);g.M(this,this.B);this.K=new O6(this.nV,0,this);g.M(this,this.K);this.C={};this.L=new g.cu(this.nE,1E3,this);g.M(this,this.L);this.I=new g.Xk(this.IN,1E3,this);g.M(this,this.I);this.N=g.y;this.PD();this.No();this.Tl()},Q8=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},FEa=function(a){Q8(a,0);
a.A.stop();R8(a,new g.HP(64))},T8=function(a,b){if(S8(a)&&!a.D){var c=null;
b&&(c={style:a.l.xi()},g.ec(c,b));a.g.AD(a.l.getVideoData(1).videoId,c);a.C=k8(a.g).l}},U8=function(a,b){var c=a.l.ag();
if(c){var d=c.he();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Ij;f=pCa(f);var n=k8(c);l=l||0;var q={videoId:k,currentIndex:l};g8(n,k,l);g.t(b)&&(e8(n,b),q.currentTime=b);g.t(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.Bg(f));o8(c,"setPlaylist",q);e||m8(c,n);R8(a,new g.HP(1))},GEa=function(a,b){if(b){var c=a.l.yc("captions","tracklist",{oz:1});
c&&c.length?(a.l.Kd("captions","track",b),a.D=!1):(a.l.Rj("captions"),a.D=!0)}else a.l.Kd("captions","track",{})},S8=function(a){return k8(a.g).videoId==a.l.getVideoData(1).videoId},R8=function(a,b){a.B.stop();
var c=a.H;if(!g.PP(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.NU(a.l,d);a.H=b;HEa(a.F,c,b)}},V8=function(a){g.U.call(this,{G:"div",
M:"ytp-remote",J:[{G:"div",M:"ytp-remote-display-status",J:[{G:"div",M:"ytp-remote-display-status-icon",J:[g.Tpa()]},{G:"div",M:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.o=new g.CV(this,250);g.M(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);IEa(this,g.KU(a))},IEa=function(a,b){if(3==a.A.Sa()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name};
c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},W8=function(a,b){g.MZ.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.H={};this.O(a,"onMdxReceiversChange",this.K);this.O(a,"presentingplayerstatechange",this.K);this.K()},X8=function(a){g.hV.call(this,a);
g.fH({YTP_MDX_CAST_SELECTOR:"\u6295\u5c04\u2026",YTP_MDX_MY_COMPUTER:"\u6b64\u8ba1\u7b97\u673a",YTP_MDX_PLAYER_ERROR:"\u6b64\u89c6\u9891\u65e0\u6cd5\u8fdc\u7a0b\u64ad\u653e\u3002",YTP_MDX_STATUS_CONNECTED_2:"\u5df2\u8fde\u63a5\u5230$RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"\u5728$RECEIVER_NAME\u4e0a\u51fa\u73b0\u9519\u8bef",YTP_MDX_STATUS_PLAYING_2:"\u6b63\u5728$RECEIVER_NAME\u4e0a\u64ad\u653e",YTP_MDX_TITLE:"\u64ad\u653e\u8bbe\u5907"});this.o={key:z6(),name:g.T("YTP_MDX_MY_COMPUTER")};this.B=null;
this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.HP(64);this.H=0;if(!g.$M(g.W(this.g))){a=this.g;var b=g.SH(a);b&&(b=b.vo())&&(b=new W8(a,b),g.M(this,b));b=new V8(a);g.M(this,b);g.bV(a,b.element,4)}},HEa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.VP(c,b))},Y8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)K8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.ag();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Zb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Ij,index:Math.max(a.g.pA(),0),currentTime:0==f?void 0:f};(d=pCa(d))&&(c.locationInfo=d);d=c}else d=null;C8("Connecting to: "+g.Bg(b));"cast-selector-receiver"==b.key?(E8(d||null),Z7()?W7().setLaunchParams(d||null):
U7("setLaunchParams called before ready.")):!d&&N8()&&B8()==b.key?g.kG("yt-remote-connection-change",!0):(K8(),E8(d||null),d=A8().je(),(d=B6(d,b.key))&&L8(d,1))}},XCa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},Y6={"'":"\\'"},JEa={},vCa={bX:"atp",w1:"ska",L0:"que",Y_:"mus",r1:"sus",jZ:"dsp"};
u6.prototype.nn=function(){var a=new u6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var H6,D6="",L6=I6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",PCa=I6("loadCastFramework")||I6("loadCastApplicationFramework"),ZDa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(O6,g.K);g.h=O6.prototype;g.h.II=function(a){this.A=arguments;this.g=!1;this.ya?this.o=(0,g.F)()+this.fd:this.ya=g.vg(this.B,this.fd)};
g.h.stop=function(){this.ya&&(g.wg(this.ya),this.ya=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();O6.ba.V.call(this)};
g.h.JI=function(){this.o?(this.ya=g.vg(this.B,this.o-(0,g.F)()),this.o=null):(this.ya=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};P6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
P6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=Q6.prototype;g.h.fi=null;g.h.yf=!1;g.h.Ak=null;g.h.rv=null;g.h.gk=null;g.h.zj=null;g.h.eh=null;g.h.Bh=null;g.h.Ei=null;g.h.Rc=null;g.h.lm=0;g.h.zf=null;g.h.Pp=null;g.h.fh=null;g.h.jl=-1;g.h.hD=!0;g.h.Ph=!1;g.h.Kr=0;g.h.bp=null;var VCa={},T6={};g.h=Q6.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.fU=function(a){a=a.target;var b=this.bp;b&&3==g.nx(a)?b.xj():this.vE(a)};
g.h.vE=function(a){try{if(a==this.Rc)a:{var b=g.nx(this.Rc),c=this.Rc.l,d=this.Rc.getStatus();if(g.yd&&!g.rc(10)||g.Ad&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ff&&!g.tx(this.Rc))break a;this.Ph||4!=b||7==c||(8==c||0>=d?this.g.sf(3):this.g.sf(2));$6(this);var e=this.Rc.getStatus();this.jl=e;var f=g.tx(this.Rc);(this.yf=200==e)?(4==b&&W6(this),this.B?(WCa(this,b,f),g.ff&&this.yf&&3==b&&(this.W.U(this.l,"tick",this.bU),this.l.start())):V6(this,f),this.yf&&!this.Ph&&(4==b?this.g.Lo(this):
(this.yf=!1,S6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.fh=3,U6(13)):(this.fh=0,U6(14)),W6(this),X6(this))}}catch(k){this.Rc&&g.tx(this.Rc)}finally{}};
g.h.bU=function(){var a=g.nx(this.Rc),b=g.tx(this.Rc);this.lm<b.length&&($6(this),WCa(this,a,b),this.yf&&4!=a&&S6(this))};
g.h.lT=function(a){Z6((0,g.z)(this.kT,this,a),0)};
g.h.kT=function(a){this.Ph||($6(this),V6(this,a),S6(this))};
g.h.uC=function(a){Z6((0,g.z)(this.jT,this,a),0)};
g.h.jT=function(a){this.Ph||(W6(this),this.yf=a,this.g.Lo(this),this.g.sf(4))};
g.h.cancel=function(){this.Ph=!0;W6(this)};
g.h.BT=function(){this.Ak=null;var a=(0,g.F)();0<=a-this.rv?(2!=this.zj&&this.g.sf(3),W6(this),this.fh=2,U6(18),X6(this)):ZCa(this,this.rv-a)};g.h=bDa.prototype;g.h.Ir=null;g.h.qe=null;g.h.cp=!1;g.h.Fy=null;g.h.Dn=null;g.h.Ns=null;g.h.Jr=null;g.h.Le=null;g.h.yg=-1;g.h.il=null;g.h.Gk=null;g.h.connect=function(a){this.Jr=a;a=b7(this.g,null,this.Jr);U6(3);this.Fy=(0,g.F)();var b=this.g.F;null!=b?(this.il=b[0],(this.Gk=b[1])?(this.Le=1,cDa(this)):(this.Le=2,d7(this))):(t6(a,"MODE","init"),this.qe=new Q6(this,void 0,void 0,void 0),this.qe.fi=this.Ir,R6(this.qe,a,!1,null,!0),this.Le=0)};
g.h.UH=function(a){if(a)this.Le=2,d7(this);else{U6(4);var b=this.g;b.Nf=b.Tg.yg;k7(b,9)}a&&this.sf(2)};
g.h.fr=function(a){return this.g.fr(a)};
g.h.abort=function(){this.qe&&(this.qe.cancel(),this.qe=null);this.yg=-1};
g.h.Ey=function(){return!1};
g.h.nC=function(a,b){this.yg=a.jl;if(0==this.Le)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Nf=this.yg;k7(c,2);return}this.il=c[0];this.Gk=c[1]}else c=this.g,c.Nf=this.yg,k7(c,2);else if(2==this.Le)if(this.cp)U6(7),this.Ns=(0,g.F)();else if("11111"==b){if(U6(6),this.cp=!0,this.Dn=(0,g.F)(),c=this.Dn-this.Fy,!g.yd||g.rc(10)||500>c)this.yg=200,this.qe.cancel(),U6(12),c7(this.g,this,!0)}else U6(8),this.Dn=this.Ns=(0,g.F)(),this.cp=!1};
g.h.Lo=function(){this.yg=this.qe.jl;if(this.qe.yf)0==this.Le?this.Gk?(this.Le=1,cDa(this)):(this.Le=2,d7(this)):2==this.Le&&((!g.yd||g.rc(10)?!this.cp:200>this.Ns-this.Dn)?(U6(11),c7(this.g,this,!1)):(U6(12),c7(this.g,this,!0)));else{0==this.Le?U6(9):2==this.Le&&U6(10);var a=this.g;a.Nf=this.yg;k7(a,2)}};
g.h.fm=function(){return this.g.fm()};
g.h.isActive=function(){return this.g.isActive()};
g.h.sf=function(a){this.g.sf(a)};g.h=e7.prototype;g.h.Rk=null;g.h.Vd=null;g.h.xc=null;g.h.Hr=null;g.h.Hn=null;g.h.Sw=null;g.h.Sn=null;g.h.Nl=0;g.h.aP=0;g.h.rd=null;g.h.Vg=null;g.h.rg=null;g.h.Th=null;g.h.Tg=null;g.h.Op=null;g.h.Mj=-1;g.h.Ez=-1;g.h.Nf=-1;g.h.mj=0;g.h.Yi=0;g.h.Rh=8;var l7=new g.Gf;g.A(eDa,g.df);g.A(fDa,g.df);g.A(gDa,g.df);g.h=e7.prototype;g.h.connect=function(a,b,c,d,e){U6(0);this.Hr=b;this.Rk=c||{};d&&g.t(e)&&(this.Rk.OSID=d,this.Rk.OAID=e);this.C?(Z6((0,g.z)(this.tx,this,a),100),kDa(this)):this.tx(a)};
g.h.tx=function(a){this.Tg=new bDa(this);this.Tg.Ir=null;this.Tg.l=this.B;this.Tg.connect(a)};
g.h.Ey=function(){return 0==this.g};
g.h.sC=function(a){this.Vg=null;nDa(this,a)};
g.h.rC=function(){this.rg=null;this.xc=new Q6(this,this.o,"rpc",this.D);this.xc.fi=null;this.xc.Kr=0;var a=this.Sw.clone();g.Im(a,"RID","rpc");g.Im(a,"SID",this.o);g.Im(a,"CI",this.Op?"0":"1");g.Im(a,"AID",this.Mj);f7(this,a);if(!g.yd||g.rc(10))g.Im(a,"TYPE","xmlhttp"),R6(this.xc,a,!0,this.Sn,!1);else{g.Im(a,"TYPE","html");var b=this.xc,c=!!this.Sn;b.zj=3;b.eh=s6(a.clone());YCa(b,c)}};
g.h.nC=function(a,b){if(0!=this.g&&(this.xc==a||this.Vd==a))if(this.Nf=a.jl,this.Vd==a&&3==this.g)if(7<this.Rh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.rg){if(this.xc)if(this.xc.gk+3E3<this.Vd.gk)h7(this),this.xc.cancel(),this.xc=null;else break a;j7(this);U6(19)}}else this.Ez=c[1],0<this.Ez-this.Mj&&37500>c[2]&&this.Op&&0==this.Yi&&!this.Th&&(this.Th=Z6((0,g.z)(this.DP,this),6E3));else k7(this,11)}else b!=JEa.eY.g&&k7(this,11);else if(this.xc==a&&
h7(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Mj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Sn=e[2],e=e[3],null!=e?this.Rh=e:this.Rh=6,this.g=3,this.rd&&this.rd.fx(),this.Sw=b7(this,this.fm()?this.Sn:null,this.Hr),oDa(this)):"stop"==e[0]&&k7(this,7):3==this.g&&("stop"==e[0]?k7(this,7):"noop"!=e[0]&&this.rd&&this.rd.bx(e),this.Yi=0)}}};
g.h.DP=function(){null!=this.Th&&(this.Th=null,this.xc.cancel(),this.xc=null,j7(this),U6(20))};
g.h.Lo=function(a){if(this.xc==a){h7(this);this.xc=null;var b=2}else if(this.Vd==a)this.Vd=null,b=1;else return;this.Nf=a.jl;if(0!=this.g)if(a.yf)1==b?(b=(0,g.F)()-a.gk,l7.dispatchEvent(new fDa(l7,a.Ei?a.Ei.length:0,b,this.mj)),g7(this),this.A.length=0):oDa(this);else{var c=a.fh,d;if(!(d=3==c||7==c||0==c&&0<this.Nf)){if(d=1==b)this.Vd||this.Vg||1==this.g||2<=this.mj?d=!1:(this.Vg=Z6((0,g.z)(this.sC,this,a),pDa(this,this.mj)),this.mj++,d=!0);d=!(d||2==b&&j7(this))}if(d)switch(c){case 1:k7(this,5);
break;case 4:k7(this,10);break;case 3:k7(this,6);break;case 7:k7(this,12);break;default:k7(this,2)}}};
g.h.qI=function(a){if(!g.Na(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.ZU=function(a){a?U6(2):(U6(1),qDa(this,8))};
g.h.fr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.hx;a.F=!1;return a};
g.h.isActive=function(){return!!this.rd&&this.rd.isActive(this)};
g.h.sf=function(a){l7.dispatchEvent(new gDa(l7,a))};
g.h.fm=function(){return!(!g.yd||g.rc(10))};
g.h=rDa.prototype;g.h.fx=function(){};
g.h.bx=function(){};
g.h.ax=function(){};
g.h.Qq=function(){};
g.h.iy=function(){return{}};
g.h.isActive=function(){return!0};g.A(m7,g.K);g.h=m7.prototype;g.h.cT=function(){this.fd=Math.min(3E5,2*this.fd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.fd+15E3*Math.random();g.du(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.fd=5E3};g.A(n7,rDa);g.h=n7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Nd=function(a){return this.o.Nd(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.bf(this.o),uDa(this),g.bf(this.l),this.l=null)};
g.h.ia=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new e7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.g;e&&(e.rd=null);d.rd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Mj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):o7(this)&&lDa(this.g,c)};
g.h.fx=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)lDa(this.g,a[b])}this.R("handlerOpened")};
g.h.ax=function(a){var b=2==a&&401==this.g.Nf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.Qq=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.iy=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.bx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),jDa(this.g)):this.R("handlerMessage",new sDa(a[0],a[1]))};
g.h.GV=function(){this.l.isActive();var a=this.g,b=0;a.xc&&b++;a.Vd&&b++;0!=b||this.connect(this.B,this.A)};p7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
p7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
p7.prototype.B=function(a){a(Error("request timed out"))};var CDa=(0,g.F)(),s7=null,v7=Array(50),u7=-1,w7=!1;g.A(x7,g.VF);x7.prototype.je=function(){return this.g};
x7.prototype.contains=function(a){return!!A6(this.g,a)};
x7.prototype.get=function(a){return a?B6(this.g,a):null};
x7.prototype.info=function(a){t7(this.D,a)};g.A(y7,g.VF);var KEa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=y7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.ya)&&this.AE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.ya)||(g.eE(this.ya),this.ya=window.NaN)};
g.h.V=function(){this.stop();y7.ba.V.call(this)};
g.h.AE=function(){this.ya=window.NaN;this.g=g.sE(q7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.IV,this),onError:(0,g.z)(this.HV,this),xd:(0,g.z)(this.JV,this)})};
g.h.IV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new v6(c))};
g.h.HV=function(a){this.g=null;a.status&&404==a.status?this.l>=KEa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=KEa[this.l],this.ya=g.cE((0,g.z)(this.AE,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.JV=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(A7,x7);g.h=A7.prototype;g.h.start=function(){z7(this)&&this.R("screenChange");!g.bH("yt-remote-lounge-token-expiration")&&GDa(this);g.eE(this.l);this.l=g.cE((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){z7(this);DDa(this,a);B7(this,!1);this.R("screenChange");b(a);a.token||GDa(this)};
g.h.remove=function(a,b){var c=z7(this);FDa(this,a)&&(B7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Jp=function(a,b,c,d){var e=z7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,B7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.eE(this.l);A7.ba.V.call(this)};
g.h.YI=function(a){z7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}B7(this,!b);b&&t7(this.D,"Missed "+b+" lounge tokens.")};
g.h.XI=function(a){t7(this.D,"Requesting lounge tokens failed: "+a)};g.A(D7,g.VF);g.h=D7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.bH("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?F7(this):(this.A=(0,g.F)()+3E5,g.aH("yt-remote-fast-check-period",this.A),this.Eu())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){C7("Updating availability on schedule.");var a=this.C(),b=g.Jb(this.g,function(b,d){return b&&!!B6(a,d)},this);
E7(this,b)};
g.h.V=function(){g.eE(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);D7.ba.V.call(this)};
g.h.Eu=function(){g.eE(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=JDa(this);if(g.Mb(a)){var b=q7(this.B,"/pairing/get_screen_availability");this.l=r7(this.B,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.IS,this,a),(0,g.z)(this.HS,this))}else E7(this,{}),F7(this)};
g.h.IS=function(a,b){this.l=null;var c=g.Qb(JDa(this));if(g.gb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;E7(this,d);F7(this)}else this.gc("Changing Screen set during request."),this.Eu()};
g.h.HS=function(a){this.gc("Screen availability failed: "+a);this.l=null;F7(this)};
g.h.gc=function(a){t7("OnlineScreenService",a)};g.A(G7,x7);g.h=G7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Jp=function(a,b,c,d){this.o.contains(a)?this.o.Jp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,t7(this.D,a),d(Error(a)))};
g.h.je=function(a){return a?this.g:g.Va(this.g,(0,g.Ld)(this.A,function(a){return!this.contains(a)},this))};
g.h.BE=function(){return(0,g.Ld)(this.je(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.CE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new y7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.bf(f);d(H7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.bf(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.LV=function(a,b,c,d){g.sE(q7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new v6(d.screen||{});if(!e.name||NDa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);NDa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(H7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
xd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.bf(this.o);g.bf(this.l);G7.ba.V.call(this)};
g.h.nJ=function(){ODa(this);this.R("screenChange");this.l.update()};
G7.prototype.dispose=G7.prototype.dispose;g.A(J7,g.VF);g.h=J7.prototype;g.h.Mo=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.pe=function(a){this.ia()||(a&&K7(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){t7(this.L,a)};
g.h.EE=function(){return null};
g.h.Lu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){K7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Lu("");J7.ba.V.call(this)};g.A(L7,J7);g.h=L7.prototype;g.h.Ku=function(a){if(this.g){if(this.g==a)return;K7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);QDa(this)};
g.h.Oj=function(a){this.info("launchWithParams no-op for Cast: "+g.Bg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.pe()},this),(0,g.z)(function(){this.pe(Error("Failed to stop receiver app."))},this)):this.pe(Error("Stopping cast device witout session."))};
g.h.Lu=g.y;g.h.V=function(){this.info("disposeInternal");g.eE(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;L7.ba.V.call(this)};
g.h.OT=function(a,b){if(!this.ia())if(b){var c=g.bx(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Bg(c));switch(d){case "mdxSessionStatus":PDa(this,c.screenId);break;default:K7(this,"Unknown youtube message: "+d)}}else K7(this,"Unable to parse message.")}else K7(this,"No data in message.")};
g.h.wy=function(a,b,c,d){MDa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(K7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.cE((0,g.z)(this.wy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.EE=function(){return this.g};
g.h.MV=function(a){this.ia()||a||(K7(this,"Cast session died."),this.pe())};g.A(M7,J7);g.h=M7.prototype;g.h.Ku=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Oj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.eE(this.C);this.A?this.A.stop((0,g.z)(this.pe,this,null),(0,g.z)(this.pe,this,"Failed to stop DIAL device.")):this.pe()};
g.h.V=function(){this.g();this.g=g.y;g.eE(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;M7.ba.V.call(this)};
g.h.PV=function(a){this.ia()||a||(K7(this,"DIAL session died."),this.g(),this.g=g.y,this.pe())};
g.h.zs=function(a){this.I=z6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,SDa(this));a(b);RDa(this)}else this.D=(0,g.z)(function(){g.eE(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,SDa(this));a(b);RDa(this)},this),this.C=g.cE((0,g.z)(function(){this.D()},this),100)};
g.h.BK=function(a,b,c){MDa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Mo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.zs(b,c)},this),(0,g.z)(function(a){K7(this,"Failed to get DIAL screen: "+a);
this.zs(b,c)},this))};g.A(N7,J7);N7.prototype.stop=function(){this.pe()};
N7.prototype.Ku=g.y;N7.prototype.Oj=function(){g.eE(this.g);this.g=window.NaN;var a=B6(this.H.je(),this.l.label);a?this.Mo(a):this.pe(Error("No such screen"))};
N7.prototype.V=function(){g.eE(this.g);this.g=window.NaN;N7.ba.V.call(this)};g.A(O7,g.VF);g.h=O7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.oC,this),(0,g.z)(this.sS,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.nQ,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ia()||(window.chrome.cast.addReceiverActionListener(this.A),zDa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.DE,this)),this.o=UDa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.Bg(a))},this)),this.R("yt-remote-cast2-availability-change",Q7(this)),b(!0))},this),(0,g.z)(function(a){this.gc("Failed to initialize API: "+g.Bg(a));
b(!1)},this))};
g.h.JU=function(a,b){P7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)P7("Unsetting old screen status: "+this.g.l.friendlyName),R7(this,null)}if(a&&b){if(!this.g){c=B6(this.l.je(),a);if(!c){P7("setConnectedScreenStatus: Unknown screen.");return}var d=TDa(this,c);d||(P7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.Bg(a))},this)));
P7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);R7(this,new N7(this.l,d),!0)}this.g.Lu(b)}else P7("setConnectedScreenStatus: no screen.")};
g.h.KU=function(a){this.ia()?this.gc("Setting connection data on disposed cast v2"):this.g?this.g.Oj(a):this.gc("Setting connection data without a session")};
g.h.OV=function(){this.ia()?this.gc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),R7(this,null)):P7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.oC,this),(0,g.z)(this.NS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.DE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Sa(g.x("yt.mdx.remote.debug.handlers_")||[],wDa);g.bf(this.g);O7.ba.V.call(this)};
g.h.gc=function(a){t7("Controller",a)};
g.h.pC=function(a,b){this.g==a&&(b||R7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.oS=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),P7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)P7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{P7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:R7(this,
new N7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:R7(this,new M7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:R7(this,new L7(this.l,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.nQ=function(a){if(this.ia())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return P7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);R7(this,new M7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.BK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.zs,b))};
g.h.oC=function(a){if(!this.ia()){P7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)P7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),R7(this,new L7(this.l,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=B6(this.l.je(),c.label);
d&&w6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(P7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.bf(this.g),this.g=new L7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.pC,this,this.g)),this.g.Oj(null));this.g.Ku(a)}}};
g.h.NV=function(){return this.g?this.g.EE():null};
g.h.NS=function(a){this.ia()||(this.gc("Failed to estabilish a session: "+g.Bg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&R7(this,null))};
g.h.sS=function(a){P7("Receiver availability updated: "+a);if(!this.ia()){var b=Q7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;Q7(this)!=b&&this.R("yt-remote-cast2-availability-change",Q7(this))}};
g.h.DE=function(){this.ia()||(this.o=UDa(this),P7("Updating custom receivers: "+g.Bg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.gc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",Q7(this)))};
O7.prototype.setLaunchParams=O7.prototype.KU;O7.prototype.setConnectedScreenStatus=O7.prototype.JU;O7.prototype.stopSession=O7.prototype.OV;O7.prototype.getCastSession=O7.prototype.NV;O7.prototype.requestSession=O7.prototype.requestSession;O7.prototype.init=O7.prototype.init;O7.prototype.dispose=O7.prototype.dispose;var X7=[];g.h=b8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";c8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Qf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+d8(this):this.H};
g.h.clone=function(){return new b8(h8(this))};g.A(j8,g.VF);g.h=j8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,p8(this,"play")):o8(this,"play"),n8(this,1,f8(k8(this))),this.R("remotePlayerChange")):l8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,p8(this,"pause")):o8(this,"pause"),n8(this,2,f8(k8(this))),this.R("remotePlayerChange")):l8(this,this.pause)};
g.h.zE=function(a){if(1==this.g){if(this.l){var b=k8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,p8(this,"seekTo",{newTime:a}))}else o8(this,"seekTo",{newTime:a});n8(this,3,a);this.R("remotePlayerChange")}else l8(this,g.Ea(this.zE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,p8(this,"stopVideo")):o8(this,"stopVideo");var a=k8(this);a.index=-1;a.videoId="";c8(a);m8(this,a);this.R("remotePlayerChange")}else l8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=k8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){t7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){t7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);o8(this,"setVolume",e)}c.muted=b;c.volume=a;m8(this,c)}else l8(this,g.Ea(this.setVolume,a,b))};
g.h.AD=function(a,b){if(1==this.g){var c=k8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Bg(b.style),g.ec(d,c.l));o8(this,"setSubtitlesTrack",d);m8(this,c)}else l8(this,g.Ea(this.AD,a,b))};
g.h.zv=function(a,b){if(1==this.g){o8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ob.id});var c=k8(this);c.audioTrackId=b.Ob.id;m8(this,c)}else l8(this,g.Ea(this.zv,a,b))};
g.h.yE=function(a,b){if(1==this.g){if(a&&b){var c=k8(this);g8(c,a,b);m8(this,c)}o8(this,"previous")}else l8(this,g.Ea(this.yE,a,b))};
g.h.xE=function(a,b){if(1==this.g){if(a&&b){var c=k8(this);g8(c,a,b);m8(this,c)}o8(this,"next")}else l8(this,g.Ea(this.xE,a,b))};
g.h.Lx=function(){1==this.g?o8(this,"dismissAutoplay"):l8(this,this.Lx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}j8.ba.dispose.call(this)};
g.h.V=function(){gEa(this);this.A=null;this.B.clear();i8(this,null);j8.ba.V.call(this)};
g.h.Av=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.wC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.jS=function(a,b){this.R(a,b)};
g.h.KP=function(a){if(!a)this.Ql(null),i8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=k8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)t7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,m8(this,b)}};
g.h.Ql=function(a){t7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),hEa(this),this.R("remotePlayerChange")};
g.h.JP=function(a){a?(hEa(this),this.R("remotePlayerChange")):this.Ql(null)};
g.h.WP=function(){var a=dEa();a&&i8(this,a)};
g.h.gc=function(a){t7("CP",a)};g.A(q8,g.VF);g.h=q8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Xa.listId=c);this.Xa.videoId=d;this.Xa.index=k||0;this.Xa.state=3;e8(this.Xa,m);this.A="UNSUPPORTED";r8("Connecting with setPlaylist and params: "+g.Bg(l));this.g.connect({method:"setPlaylist",
params:g.Bg(l)},a,DCa())}else r8("Connecting without params"),this.g.connect({},a,DCa());jEa(this)};
g.h.dispose=function(){this.ia()||(this.R("beforeDispose"),s8(this,3));q8.ba.dispose.call(this)};
g.h.V=function(){t8(this);v8(this);u8(this);g.eE(this.H);this.H=window.NaN;g.eE(this.I);this.I=window.NaN;this.o=null;g.FF(this.T);this.T.length=0;this.g.dispose();q8.ba.V.call(this);this.A=this.D=this.l=this.Xa=this.g=null};
g.h.NI=function(){this.C(2)};
g.h.OP=function(){r8("Channel opened");this.N&&(this.N=!1,u8(this),this.L=g.cE((0,g.z)(function(){r8("Timing out waiting for a screen.");this.C(1)},this),15E3));
HCa(tDa(this.g),this.Z)};
g.h.LP=function(){r8("Channel closed");(0,window.isNaN)(this.B)?G6(!0):G6();this.dispose()};
g.h.MP=function(a){G6();(0,window.isNaN)(this.F())?(r8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,r8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),s8(this,2))};
g.h.NP=function(a){a.params?r8("Received: action="+a.action+", params="+g.Bg(a.params)):r8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.bx(a.params.devices);this.l=(0,g.G)(a,function(a){return new u6(a)});
a=!!g.Ja(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
mEa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
mEa(this,!1);break;case "remoteConnected":var b=new u6(g.bx(a.params.device));g.Ja(this.l,function(a){return b?a.id==b.id:!1})||g.Qa(this.l,b);
break;case "remoteDisconnected":b=new u6(g.bx(a.params.device));g.Ua(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":oEa(this,a);break;case "nowPlaying":qEa(this,a);break;case "onStateChange":pEa(this,a);break;case "onAdStateChange":rEa(this,a);break;case "onVolumeChanged":sEa(this,a);break;case "onSubtitlesTrackChanged":nEa(this,a);break;case "nowAutoplaying":tEa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":uEa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:r8("Unrecognized action: "+a.action)}};
g.h.tU=function(){if(this.o){var a=this.o;this.o=null;this.Xa.videoId!=a&&w8(this,"getNowPlaying")}};
q8.prototype.subscribe=q8.prototype.subscribe;q8.prototype.unsubscribeByKey=q8.prototype.Nd;q8.prototype.fa=function(){var a=3;this.ia()||(a=0,(0,window.isNaN)(this.F())?o7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
q8.prototype.getProxyState=q8.prototype.fa;q8.prototype.C=function(a){r8("Disconnecting with "+a);t8(this);this.R("beforeDisconnect",a);1==a&&G6();uDa(this.g,a);this.dispose()};
q8.prototype.disconnect=q8.prototype.C;q8.prototype.ea=function(){var a=this.Xa;this.o&&(a=this.Xa.clone(),g8(a,this.o,a.index));return h8(a)};
q8.prototype.getPlayerContextData=q8.prototype.ea;
q8.prototype.ma=function(a){var b=new b8(a);b.videoId&&b.videoId!=this.Xa.videoId&&(this.o=b.videoId,g.eE(this.H),this.H=g.cE((0,g.z)(this.tU,this),5E3));var c=[];this.Xa.listId==b.listId&&this.Xa.videoId==b.videoId&&this.Xa.index==b.index||c.push("remoteQueueChange");this.Xa.g==b.g&&this.Xa.volume==b.volume&&this.Xa.muted==b.muted&&f8(this.Xa)==f8(b)&&g.Bg(this.Xa.l)==g.Bg(b.l)||c.push("remotePlayerChange");this.Xa.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
q8.prototype.setPlayerContextData=q8.prototype.ma;q8.prototype.X=function(){var a=this.g.C.id,b=g.Ja(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
q8.prototype.getOtherConnectedRemoteId=q8.prototype.X;q8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
q8.prototype.getReconnectTimeout=q8.prototype.F;q8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
q8.prototype.getAutoplayMode=q8.prototype.Y;q8.prototype.aa=function(){return this.D||""};
q8.prototype.getAutoplayVideoId=q8.prototype.aa;q8.prototype.ra=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.eu(a.g);a.start()}};
q8.prototype.reconnect=q8.prototype.ra;q8.prototype.ha=function(a,b){w8(this,a,b);lEa(this)};
q8.prototype.sendMessage=q8.prototype.ha;g.A(x8,x7);g.h=x8.prototype;g.h.je=function(a){return this.ed.$_gs(a)};
g.h.contains=function(a){return!!this.ed.$_c(a)};
g.h.get=function(a){return this.ed.$_g(a)};
g.h.start=function(){this.ed.$_st()};
g.h.add=function(a,b,c){this.ed.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ed.$_r(a,b,c)};
g.h.Jp=function(a,b,c,d){this.ed.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.ed.$_ubk(this.l[a]);this.l.length=0;this.ed=null;x8.ba.V.call(this)};
g.h.KV=function(){this.R("screenChange")};
g.h.KR=function(){this.R("onlineScreenChange")};
G7.prototype.$_st=G7.prototype.start;G7.prototype.$_gspc=G7.prototype.LV;G7.prototype.$_gsppc=G7.prototype.CE;G7.prototype.$_c=G7.prototype.contains;G7.prototype.$_g=G7.prototype.get;G7.prototype.$_a=G7.prototype.add;G7.prototype.$_un=G7.prototype.Jp;G7.prototype.$_r=G7.prototype.remove;G7.prototype.$_gs=G7.prototype.je;G7.prototype.$_gos=G7.prototype.BE;G7.prototype.$_s=G7.prototype.subscribe;G7.prototype.$_ubk=G7.prototype.Nd;var y8=null,z8=null,O8=null,D8=[];g.p(P8,g.K);g.h=P8.prototype;
g.h.V=function(){g.K.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.mC,this);this.g.unsubscribe("remotePlayerChange",this.Tl,this);this.g.unsubscribe("remoteQueueChange",this.No,this);this.g.unsubscribe("autoplayUpNext",this.JB,this);this.g.unsubscribe("previousNextChange",this.jC,this);this.g.unsubscribe("nowAutoplaying",this.bC,this);this.g.unsubscribe("autoplayDismissed",this.IB,this);this.g=this.F=null};
g.h.KA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(S8(this)){if(!k8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":k8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.xj(c[0],c[1]);break;case "control_subtitles_set_track":T8(this,c[0]);break;case "control_set_audio_track":c=c[0],S8(this)&&this.g.zv(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();U8(this,0==c?void 0:c);break;case "control_seek":U8(this,c[0]);break;case "control_subtitles_set_track":T8(this,c[0]);break;case "control_set_audio_track":c=c[0],S8(this)&&this.g.zv(this.l.getVideoData(1).videoId,c)}};
g.h.IP=function(a){this.K.II(a)};
g.h.nV=function(a){this.KA("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.PD=function(){var a=this.l.yc("captions","track");g.Xb(a)||T8(this,a)};
g.h.ZB=function(a){if(S8(this)){this.g.unsubscribe("remotePlayerChange",this.Tl,this);var b=Math.round(a.volume);a=!!a.muted;var c=k8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.Tl,this)}};
g.h.dR=function(){g.Xb(this.C)||GEa(this,this.C);this.D=!1};
g.h.mC=function(a,b){this.B.stop();2==b&&this.MD()};
g.h.Tl=function(){if(S8(this)){this.A.stop();var a=k8(this.g);switch(a.g){case 1081:case 1:R8(this,new g.HP(8));this.LD();break;case 1085:case 3:R8(this,new g.HP(9));break;case 1083:case 0:R8(this,new g.HP(2));this.I.stop();Q8(this,this.l.getVideoData().lengthSeconds);break;case 1084:R8(this,new g.HP(4));break;case 2:R8(this,new g.HP(4));Q8(this,f8(a));break;case -1:R8(this,new g.HP(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},R8(this,new g.HP(128,a))}a=
k8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,GEa(this,a));a=k8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.L.isActive()||this.nE()}else FEa(this)};
g.h.jC=function(){this.l.R("mdxpreviousnextchange")};
g.h.No=function(){S8(this)||FEa(this)};
g.h.TH=function(){this.g.Lx()};
g.h.JB=function(a){a&&(a=g.sE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.oT,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.oT=function(a,b){var c=new g.xO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.bC=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.IB=function(){this.l.R("mdxautoplaycanceled")};
g.h.IN=function(a,b){-1==k8(this.g).g?U8(this,a):b&&this.g.zE(a)};
g.h.nE=function(){if(S8(this)){var a=k8(this.g);this.o.Ca(this.T);a.muted?this.l.mute():this.l.cg();this.l.setVolume(a.volume);this.T=this.o.O(this.l,"onVolumeChange",this.ZB)}};
g.h.LD=function(){this.A.stop();if(!this.g.ia()){var a=k8(this.g);a.kb()&&R8(this,new g.HP(8));Q8(this,f8(a));this.A.start()}};
g.h.MD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(V8,g.U);V8.prototype.B=function(a){IEa(this,a.state)};g.p(W8,g.MZ);W8.prototype.K=function(){var a=this.o.yc("remote","receivers");a&&1<a.length&&!this.o.yc("remote","quickCast")?(this.H=g.jb(a,this.C,this),g.NZ(this,(0,g.G)(a,this.C)),a=this.o.yc("remote","currentReceiver"),this.rf(this.C(a)),this.enable(!0)):this.enable(!1)};
W8.prototype.C=function(a){return a.key};
W8.prototype.qf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.H[a].name};
W8.prototype.ud=function(a){g.MZ.prototype.ud.call(this,a);this.o.Kd("remote","currentReceiver",this.H[a]);this.B.Pb()};g.p(X8,g.hV);g.h=X8.prototype;g.h.create=function(){zEa(g.NM(g.W(this.g)));this.C.push(g.gG("yt-remote-before-disconnect",this.EP,this));this.C.push(g.gG("yt-remote-connection-change",this.tS,this));this.C.push(g.gG("yt-remote-receiver-availability-change",this.kC,this));this.C.push(g.gG("yt-remote-auto-connect",this.rS,this));this.C.push(g.gG("yt-remote-receiver-resumed",this.qS,this));this.kC()};
g.h.load=function(){this.g.Ct();g.hV.prototype.load.call(this);this.B=new P8(this,this.g,this.l);var a=(a=EEa())?a.currentTime:0;var b=N8()?new j8(I8(),void 0):null;0==a&&b&&(a=f8(k8(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));HEa(this,this.D,this.D);g.c0(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.cf(this.B,this.l);this.l=this.B=null;g.hV.prototype.unload.call(this);g.c0(this.g.app,5)};
g.h.V=function(){g.hG(this.C);g.hV.prototype.V.call(this)};
g.h.Jl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.KA.apply(this.B,[a].concat(g.oa(c)))};
g.h.EI=function(){return this.loaded?this.B.suggestion:null};
g.h.Qf=function(){return this.l?k8(this.l).Qf:!1};
g.h.hasNext=function(){return this.l?k8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.wN=function(){var a=k8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.gd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+d8(a):a.A,isPeggedToLive:1>=(a.C?a.o+d8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+d8(a):a.o,seekableStart:0<a.B?a.B+d8(a):a.B}};
g.h.xN=function(){this.l&&this.l.xE()};
g.h.yN=function(){this.l&&this.l.yE()};
g.h.EP=function(a){1==a&&(this.I=this.l?k8(this.l):null)};
g.h.tS=function(){var a=N8()?new j8(I8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.bf(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.nA(a.videoId,f8(a)));this.g.R("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.kC=function(){this.F=[this.o].concat(BEa());var a=J8()||this.o;Y8(this,a);this.g.ua("onMdxReceiversChange")};
g.h.rS=function(){var a=J8();Y8(this,a)};
g.h.qS=function(){this.A=J8()};
g.h.vN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?$7():Y8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&$7(),!0):!1}};
g.h.zN=function(){o8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Oc=function(){return!1};g.aY.remote=X8;})(_yt_player);
